### ISSUE TITLE
Unserialize Error During Migration 1.9.3.6 > 2.2

### ISSUE THREAD

**Issue by ArthurSCD** [magento/data-migration-tool#434]
```
[2017-12-22 03:24:17][DEBUG][mode: data][stage: data migration][step: Map Step][table: sales_flat_order_item]: migrating
50% [==============>-------------] Remaining Time: 3 secs

  [Exception]
  Notice: unserialize(): Error at offset 297 of 714 bytes in /home/user/public_html/datadev/vendor/magento/data-migration-tool/src/Migration/Handler/SerializeToJson/
  SalesOrderItem.php on line 28
```
Tried finding similar issues and attempted a few things like 
```            
<transform>
                <field>sales_flat_order_item.weee_tax_applied</field>
                <handler class="Migration\Handler\SerializeToJson">
                <param name="gnoreBrokenData" value="true" />
                </handler>
            </transform>
```
in `map.xml.dist` (is that the correct place to edit? inside the 1.9.3.6 folder?) - this didn't work though, did I do something wrong? 

I have 25k rows in `sales_flat_order_item` so pretty rough to do a manual search for anything amiss in `weee_tax_applied` I tried `SELECT * FROM sales_flat_order_item WHERE weee_tax_applied REGEXP '^[0-9]+\.?[0-9]*$'` which returned nothing.

**Comment by molsm** [comment]
Done quick look on your code..you have missed `i`...but I am not sure if it will help you.

` <param name="gnoreBrokenData" value="true" />`

must be 

` <param name="ignoreBrokenData" value="true" />`

**Comment by ArthurSCD** [comment]
I thought `gnore` was strange as well, but I put it there because it was in 2 separate issue threads by vic who seems to answer a lot and has a magento logo so kinda assumed he was part of the dev team. 

Either way I tried `<param name="ignoreBrokenData" value="true" />` and error persists

**Comment by ArthurSCD** [comment]
I found `sales_float_order_item.production_options` is the offender, but when I try to ignore data it just simply won't work.

```            <transform>
                <field>sales_flat_order_item.product_options</field>
                <handler class="\Migration\Handler\SerializeToJson\SalesOrderItem">
                    <param name="IgnoreBrokenData" value="true" />
                </handler>
            </transform>```
I tried 
```            <transform>
                <field>sales_flat_order_item.product_options</field>
                <handler class="\Migration\Handler\SerializeToJson\SalesOrderItem">
                    <param name="gnoreBrokenData" value="true" />
                </handler>
            </transform>
```
Too.
