### ISSUE TITLE
SQLSTATE[42000] : 1701 - Cannot truncate table referenced in foreign key constraint (`entity_type_id`) [Magento 1.9.2.4 -> 2.2.3] 

### ISSUE THREAD

**Issue by SaintLuticriss** [magento/data-migration-tool#493]
We're performing an upgrade (on our test server first, of course) to Magento 2.2.3 but get this error. I hope it's something simple I'm just not understanding. We only use one extension in Magento 1.9.2.4: [Dependent Custom Options by Pektsekye](https://marketplace.magento.com/pektsekye-dependent-custom-options.html). However, I followed the instructions closely and wrote the appropriate \<ignore\> tags in the *map.xml* file to ignore the extension's few additional database tables. We're running PHP 7.1.14 with 2GB RAM. Below is the trace: 

```vim
[mode: data][stage: integrity check][step: Data Integrity Step]: completed
[mode: data][stage: integrity check][step: EAV Step]: completed
[mode: data][stage: integrity check][step: Customer Attributes Step]: completed
[mode: data][stage: integrity check][step: Map Step]: completed
[mode: data][stage: integrity check][step: Url Rewrite Step]: completed
[mode: data][stage: integrity check][step: Log Step]: completed
[mode: data][stage: integrity check][step: Ratings Step]: completed
[mode: data][stage: integrity check][step: ConfigurablePrices step]: completed
[mode: data][stage: integrity check][step: OrderGrids Step]: completed
[mode: data][stage: integrity check][step: Tier Price Step]: completed
[mode: data][stage: integrity check][step: SalesIncrement Step]: completed
[mode: data][stage: setup triggers] [step: Stage]: completed
[mode: data][stage: data migration] [step: EAV Step]: started
14% [====>-----------------------] Remaining Time: < 1 sec

______________________________________________________________________________________________________________________________________________________________________________________
  [Zend_Db_Statement_Exception]
  SQLSTATE[42000]: Syntax error or access violation: 1701 Cannot truncate a table referenced in a foreign key constraint (`magento2_db`.`mg_eav_attribute`, CONSTRAINT `MG_EAV_ATTR
  IBUTE_ENTITY_TYPE_ID_EAV_ENTITY_TYPE_ENTITY_TYPE_ID` FOREIGN KEY (`entity_type_id`) REFERENCES `magento2_db`.`mg_eav_entity_type` (`e), query was: TRUNCATE TABLE `mg_eav_entity_
  type`
______________________________________________________________________________________________________________________________________________________________________________________

Exception trace:
 () at /{magento root}/vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php:235
 Zend_Db_Statement_Pdo->_execute() at /{magento root}/vendor/magento/framework/DB/Statement/Pdo/Mysql.php:93
 Magento\Framework\DB\Statement\Pdo\Mysql->_execute() at /{magento root}/vendor/magento/zendframework1/library/Zend/Db/Statement.php:303
 Zend_Db_Statement->execute() at /{magento root}/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php:480
 Zend_Db_Adapter_Abstract->query() at /{magento root}/vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php:238
 Zend_Db_Adapter_Pdo_Abstract->query() at /{magento root}/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php:517
 Magento\Framework\DB\Adapter\Pdo\Mysql->_query() at /{magento root}/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php:580
 Magento\Framework\DB\Adapter\Pdo\Mysql->query() at /{magento root}/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php:2535
 Magento\Framework\DB\Adapter\Pdo\Mysql->truncateTable() at /{magento root}/vendor/magento/data-migration-tool/src/Migration/ResourceModel/Adapter/Mysql.php:191
 Migration\ResourceModel\Adapter\Mysql->deleteAllRecords() at /{magento root}/vendor/magento/data-migration-tool/src/Migration/ResourceModel/Destination.php:63
 Migration\ResourceModel\Destination->clearDocument() at /{magento root}/vendor/magento/data-migration-tool/src/Migration/Step/Eav/Data.php:233
 Migration\Step\Eav\Data->migrateEntityTypes() at /{magento root}/vendor/magento/data-migration-tool/src/Migration/Step/Eav/Data.php:188
 Migration\Step\Eav\Data->perform() at /{magento root}/vendor/magento/data-migration-tool/src/Migration/Mode/AbstractMode.php:79
 Migration\Mode\AbstractMode->runStage() at /{magento root}/vendor/magento/data-migration-tool/src/Migration/Mode/Data.php:119
 Migration\Mode\Data->runData() at /{magento root}/vendor/magento/data-migration-tool/src/Migration/Mode/Data.php:69
 Migration\Mode\Data->run() at /{magento root}/vendor/magento/data-migration-tool/src/Migration/Console/MigrateDataCommand.php:51
 Migration\Console\MigrateDataCommand->execute() at /{magento root}/vendor/symfony/console/Command/Command.php:242
 Symfony\Component\Console\Command\Command->run() at /{magento root}/vendor/symfony/console/Application.php:843
 Symfony\Component\Console\Application->doRunCommand() at /{magento root}/vendor/symfony/console/Application.php:193
 Symfony\Component\Console\Application->doRun() at /{magento root}/vendor/magento/framework/Console/Cli.php:104
 Magento\Framework\Console\Cli->doRun() at /{magento root}/vendor/symfony/console/Application.php:117
 Symfony\Component\Console\Application->run() at /{magento root}/bin/magento:23

______________________________________________________________________________________________________________________________________________________________________________________
  [PDOException]
  SQLSTATE[42000]: Syntax error or access violation: 1701 Cannot truncate a table referenced in a foreign key constraint (`magento2_db`.`mg_eav_attribute`, CONSTRAINT `MG_EAV_ATTR
  IBUTE_ENTITY_TYPE_ID_EAV_ENTITY_TYPE_ENTITY_TYPE_ID` FOREIGN KEY (`entity_type_id`) REFERENCES `magento2_db`.`mg_eav_entity_type` (`e)
______________________________________________________________________________________________________________________________________________________________________________________

Exception trace:
 () at /{magento root}/vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php:228
 PDOStatement->execute() at /{magento root}/vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php:228
 Zend_Db_Statement_Pdo->_execute() at /{magento root}/vendor/magento/framework/DB/Statement/Pdo/Mysql.php:93
 ... {the lines from here forward are identical to the exception trace up above}...
 Symfony\Component\Console\Application->run() at /{magento root}/bin/magento:23

```
We've read a couple other forums with suggestions like "change the *bulk_size* variable in the *config.xml* file" (we did, but it did not seem to affect anything), and "Disable Foreign Key Constraint checks" (didn't know where that needed to be done, but another user said that was already the case by default.) Any help will be greatly appreciated! =D

**Comment by SaintLuticriss** [comment]
Is this a tough question and people still looking into it? Or is there really a simple answer for this question and I'm just getting a room full of eyerolls? Or is there only a couple people that oversee/support this and my issue is a non-priority? 
My boss is getting disgruntled that we can't upgrade. He is especially upset with me since I was the one who recommended Magento, in spite of his son's recommendation for "Woo Commerce". I hope we can see a fix for it soon. >.<;;

**Comment by victor-v-rad** [comment]
Hi

Have you resolved your issue? Yes the tool disables foreign checks during migration so probably the problem because of permissions of your account

**Comment by SaintLuticriss** [comment]
Greetings!
Unfortunately we have not found a fix yet. We are a smaller company without "the best" programmers (myself included.)
I believe the User that the tool is configured to use already has all permissions. Is there an effective way to double check that? (I will go see what I can find right now, but I do believe it already has all permissions. I'll be right back.)

**Comment by SaintLuticriss** [comment]
After running "bin/magento migrate:data -r vendor/magento/data-migration-tool/etc/opensource-to-opensource/1.9.2.4/config.xml" again, I'm getting a new set of errors. I'll reset the server and try again. >.<

**Comment by SaintLuticriss** [comment]
After: 
1. Resetting the hosting server; [15 minutes]
2. Re-keying the SSL Certificate; [1 hour]
3. Restoring our Magento 1 Database backup; [1 hour]
4. (Re-)Creating and permitting a MySQL Database User to the database; [10 minutes]
5. Restoring our "Home Directory" site files backup; [1 hour]
5. Emptying the Magento 1 "vars" cache, log, report, and session folders; [15 minutes]
6. Logging into the restored Magento 1 admin dashboard to:
-- "Reindex Data"
-- "Flush Magento Cache"
-- "Refresh All" in Cache Management [10 minutes]
7. Logging into phpMyAdmin to empty these bulky/non-essential tables: [15 minutes]
-- log_customer
-- log_quote
-- log_summary
-- log_summary_type
-- log_url
-- log_url_info
-- log_visitor
-- log_visitor_info
-- log_visitor_online
-- report_compared_product_index
-- report_event
-- report_viewed_product_index
8. Changing our server PHP version from 5.5 to 7.1 [10 minutes]
9. Installing Magento 2 [15 minutes]
10. Adding the MySQL Database User to the newly-created Magento 2 database. [5 minutes]
11. Using PuTTY to SSH into the server to install the [appropriate edition of] Data Migration Tool; [10 minutes]
12. Changing the Data Migration Tool's __config.xml__ <database host="_value_" ...> from "_localhost_" to "_127.0.0.1_" in both the \<source\> and \<destination\> (to bypass the "_SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/tmp/mysql.sock'_" error); [10 minutes]
13. Inserting the other necessary config settings (source and destination database names, usernames, and user passwords; adding the crypt key from Magento 1 and removing ".dist" extension from the map_file location) [10 minutes]
14. Adding to the _map.xml_ the appropriate document and field \<ignore\> rules for our extension. [1 hour]
And;
15. Running the Data Migration Tool once again; [1 hour]

The migration seemed to finally work... I don't know what part was so different to cause it to function correctly, but it seemed to work after the reset and retry. And so a leave a _somewhat_ step-by-step walk-through for any future flounderers. I hope it helps someone perchance. Though I feel like I'm probably the last business online to be upgrading their Magento from 1 to 2. ^^;;

**Comment by victor-v-rad** [comment]
Thank you @SaintLuticriss for providing this guide. It will be helpful for other uses with similar issue

**Comment by not-art** [comment]
Hey Victor,

Sorry to comment on a closed issue, but this seems to actually be a bug & shouldn't have been closed. Let me know if it's more useful to submit a fresh issue & I'll re-post this on a new bug.

**Our source & destination magento versions:**
Source M1 Commerce: 1.14.4.0
Destination M2 Commerce: 2.3.2
Data Migration Tool: 2.3.2

We're running our 3rd test migration and have replicated the originally issue consistently:

* If you run the "migrate:data" step without fixing source/destination mapping warnings, and then fix your mapping warnings, you can successfully run the "migrate:data" step without the above error.
* If you already know your mapping issues and correct them in map.xml ahead of time, the first run of the "migrate:data" step will get past the integrity checks, it will set up the triggers & CL tables on the source DB, and then bomb out when starting the data step of the EAV migration with the originally-reported error regarding FK constraints / unable to truncate.
  * If you re-run the same "migrate:data" command again after it bombs out for the FK constraint issue, it gets past the integrity checks quickly, having already ran them, and then successfully completes the EAV step / continues on with the migration.

We could reproduce the 2nd scenario consistently, over and over; we would clean up our source DB, delete and re-create the destination m2 database with a vanilla install / fresh tables, and consistently have it bomb-out after the integrity checks at the EAV step.

On the 1st-mentioned scenario, we did NOT have the EAV FK constraint error when re-running "migrate:data" after fixing the unmapped source/destination warnings; it ran through the EAV step after quickly skipping past the integrity checks & trigger setup it had already completed from the first run.

The common-thread between scenario 1 & 2:
* 2nd (and continued) runs of the "migrate:data" step always succeed without the "can't truncate, FK Constraint" error.

**This, to us, implies some permissions or constraint-related bug caused by the data integrity and/or trigger setup steps on the initial, fresh, first run of the "migrate:data" step of the tool... Something like the mysql root user (who for us is a full db owner / has all rights, so nothing weird there) is losing it's privileges or something similar after the first time the data integrity and/or trigger setup is run for a fresh m2 migration.**

We don't know what the underlying issue is, but it's isolated to something with the steps LEADING UP to the first attempt to migrate EAV data. 

As mentioned, re-running the "migrate:data" step a 2nd time, after the initial FK integrity warning post-integrity/trigger setup, does NOT throw the error & the migration tool continues on without issue. 

We can consistently reproduce this scenario in our staging environment by dropping our destination m2 db and re-installing a fresh m2 instance / dropping our source m1 triggers/tables added by the data migration tool, and re-running a fresh migration:

1. migrate:settings (succeeds without issue)
2. migrate:data (bombs out on first run after integrity & trigger setup on the first data migration step, EAV
3. re-running the migrate:data step right after that error causes the tool to not throw the error & succeed as intended.

We also think it's related to data integrity, as the first run of the integrity check spits out every url rewrite to the console, while the 2nd run does not / seems to quickly get past the url re-write data integrity check- so to us, that implies it's not validating data integrity (as it already did so the first run), hence the 2nd run not being impacted by whatever the initial data ingrity / trigger setup is doing behind the scenes with the connection string...?

Here's a console dump proving this scenario. You'll see my first run of "migrate:data" bombs out with the "Cant truncate eav_attribute..." FK error, and then I re-run the tool and it does NOT throw the error / completed the EAV data migration.

Very very odd, but very very repeatable.

EG:

> [2019-09-12 00:49:25][INFO][mode: data][stage: integrity check][step: Log Step]: started
100% [============================] Remaining Time: < 1 sec
[2019-09-12 00:49:26][INFO][mode: data][stage: integrity check][step: Ratings Step]: started
100% [============================] Remaining Time: < 1 sec
[2019-09-12 00:49:26][INFO][mode: data][stage: integrity check][step: SalesOrder Step]: started
100% [============================] Remaining Time: < 1 sec
[2019-09-12 00:49:26][INFO][mode: data][stage: integrity check][step: ConfigurablePrices step]: started
100% [============================] Remaining Time: < 1 sec
[2019-09-12 00:49:26][INFO][mode: data][stage: integrity check][step: OrderGrids Step]: started
100% [============================] Remaining Time: < 1 sec
[2019-09-12 00:49:26][INFO][mode: data][stage: integrity check][step: Tier Price Step]: started
100% [============================] Remaining Time: < 1 sec
[2019-09-12 00:49:26][INFO][mode: data][stage: integrity check][step: SalesIncrement Step]: started
100% [============================] Remaining Time: < 1 sec
[2019-09-12 00:49:26][INFO][mode: data][stage: integrity check][step: Inventory Step]: started
100% [============================] Remaining Time: < 1 sec
[2019-09-12 00:49:26][INFO][mode: data][stage: integrity check][step: VisualMerchandiser Step]: started
100% [============================] Remaining Time: < 1 sec
[2019-09-12 00:49:26][INFO][mode: data][stage: setup triggers][step: Stage]: started
100% [============================] Remaining Time: < 1 sec
**[2019-09-12 00:49:33][INFO][mode: data][stage: data migration][step: EAV Step]: started
12% [===>------------------------] Remaining Time: < 1 sec**
In Mysql.php line 110:

>SQLSTATE[42000]: Syntax error or access violation: 1701 Cannot truncate a table referenced in a foreign key constraint (`magento2`.`eav_attribute`, CONSTRAINT `EAV_ATTRIBUTE_ENTITY_TYPE_ID_EAV_ENTITY_TYPE_ENTITY_TYPE_ID` FOREIGN KEY (`entity_type_id`) REFERENCES `magento2`.`eav_entity_type` (`entity_type_id`)), query was: TRUNCATE TABLE `ea
  v_entity_type`

>In Mysql.php line 91:

>**SQLSTATE[42000]: Syntax error or access violation: 1701 Cannot truncate a table referenced in a foreign key constraint (`magento2`.`eav_attribute`, CONSTRAINT `EAV_ATTRIBUTE_ENTITY_TYPE_ID_EAV_ENTITY_TYPE_ENTITY_TYPE_ID` FOREIGN KEY (`entity_type_id`) REFERENCES `magento2`.`eav_entity_type` (`entity_type_id`))**

>migrate:data [-r|--reset] [-a|--auto] [--] <config>

>root@magento-644bb57845-r6pzt:/var/www/html/magento2# bin/magento migrate:data /var/www/html/magento2/vendor/magento/data-migration-tool/etc/commerce-to-commerce/1.14.4.0/config.xml.dist

>[2019-09-12 00:50:10][INFO][mode: data][stage: integrity check][step: Data Integrity Step]: started
[2019-09-12 00:50:10][INFO][mode: data][stage: integrity check][step: EAV Step]: started
[2019-09-12 00:50:10][INFO][mode: data][stage: integrity check][step: Custom Customer Attributes Step]: started
[2019-09-12 00:50:10][INFO][mode: data][stage: integrity check][step: Customer Attributes Step]: started
[2019-09-12 00:50:10][INFO][mode: data][stage: integrity check][step: Map Step]: started
[2019-09-12 00:50:10][INFO][mode: data][stage: integrity check][step: Url Rewrite Step]: started
[2019-09-12 00:50:10][INFO][mode: data][stage: integrity check][step: Log Step]: started
[2019-09-12 00:50:10][INFO][mode: data][stage: integrity check][step: Ratings Step]: started
[2019-09-12 00:50:10][INFO][mode: data][stage: integrity check][step: SalesOrder Step]: started
[2019-09-12 00:50:10][INFO][mode: data][stage: integrity check][step: ConfigurablePrices step]: started
[2019-09-12 00:50:10][INFO][mode: data][stage: integrity check][step: OrderGrids Step]: started
[2019-09-12 00:50:10][INFO][mode: data][stage: integrity check][step: Tier Price Step]: started
[2019-09-12 00:50:10][INFO][mode: data][stage: integrity check][step: SalesIncrement Step]: started
[2019-09-12 00:50:10][INFO][mode: data][stage: integrity check][step: Inventory Step]: started
[2019-09-12 00:50:10][INFO][mode: data][stage: integrity check][step: VisualMerchandiser Step]: started
[2019-09-12 00:50:10][INFO][mode: data][stage: setup triggers][step: Stage]: started
[2019-09-12 00:50:10][INFO][mode: data][stage: data migration][step: EAV Step]: started
100% [============================] Remaining Time: < 1 sec
[2019-09-12 00:50:13][INFO][mode: data][stage: volume check][step: EAV Step]: started
100% [============================] Remaining Time: < 1 sec
[2019-09-12 00:50:13][INFO][mode: data][stage: data migration][step: Custom Customer Attributes Step]: started

**Comment by victor-v-rad** [comment]
This issue #692 seems pretty similar. Could it be caused by losing MySQL connection session?

**Comment by not-art** [comment]
Seems you are right, Victor. We just ran our migration on a more-stable box; we had been testing running it in a kubernetes-based docker container, and swapped it out for an AWS-based server with docker installed on it, rather than our WIP kubernetes pod.

Thanks / sorry for noise on the older stories; we're wanting to share as much with other migrating devs as we can. :)

**Comment by victor-v-rad** [comment]
Knowledge sharing is important here. So thank you for your efforts @not-art !

**Comment by dpolt-cl** [comment]
Sorry to comment on a closed issue guys. I though it might still be helpful to someone.

The error happens when Pdo reconnects to MySQL in case of lost connection in vendor/magento/framework/DB/Adapter/Pdo/Mysql.php:
```
                // Check to reconnect
                if ($pdoException && $triesCount < self::MAX_CONNECTION_RETRIES
                    && in_array($pdoException->errorInfo[1], $connectionErrors)
                ) {
                    $retry = true;
                    $triesCount++;
                    $this->closeConnection();

                    $this->_connect();
                }
```

The \Magento\Framework\DB\Adapter\Pdo\Mysql::_connect has the following code:
```
        if (isset($this->_config['initStatements'])) {
            $statements = $this->_splitMultiQuery($this->_config['initStatements']);
            foreach ($statements as $statement) {
                $this->_query($statement);
            }
        }
```

Unfortunately, the data migration tool does not pass the 'initStatements' to the Pdo and choses to execute the init statements on it's own in \Migration\ResourceModel\Adapter\Pdo\MysqlBuilder::runInitStatements
```
        $initStatements = $this->config->getOption('init_statements_' . $resourceType);
        foreach (explode(';', $initStatements) as $initStatement) {
            if (!empty($initStatement)) {
                $instance->query($initStatement);
            }
        }
```

Which does not get executed in the case of reconnection.

Also, turning the foreign keys off is done not as part of the init statements and hardcoded in \Migration\ResourceModel\Adapter\Mysql::__construct:
```
        $this->resourceAdapter = $mysqlBuilder->build($resourceType);
        $this->setForeignKeyChecks(0);
```
Which also does not get executed upon reconnection.

I implemented a patch with a quick fix that, however, **requires** to have `SET FOREIGN_KEY_CHECKS = 0;` added to `init_statements_destination` in the migration config.xml

[fix_data_migration_foreign_keys_check.txt](https://github.com/magento/data-migration-tool/files/5059980/fix_data_migration_foreign_keys_check.txt)

Hope this helps.

**Comment by zaximus84** [comment]
@dpolt-cl  Your patched worked for me. Thanks for providing such a thorough description of the problem.

**Comment by vananin** [comment]
Unfortunately, previously described methods did not resolve the issue for me. I fixed it by adding `SET FOREIGN_KEY_CHECKS = 0;` right before truncating. 

`vendor/magento/data-migration-tool/src/Migration/ResourceModel/Adapter/Mysql.php`

```
    /**
     * @inheritdoc
     */
    public function deleteAllRecords($documentName)
    {
        $this->resourceAdapter->exec('SET FOREIGN_KEY_CHECKS = 0;');
        $this->resourceAdapter->truncateTable($documentName);
    }
```
Same for other processes, e.g.
```
    public function insertRecords($documentName, $records, $updateOnDuplicate = false)
    {
        $this->resourceAdapter->exec('SET FOREIGN_KEY_CHECKS = 0;');
        ...
    }

    protected function insertMultiple($documentName, $records)
    {
        $this->resourceAdapter->exec('SET FOREIGN_KEY_CHECKS = 0;');
        ...
    }

    public function insertFromSelect(\Magento\Framework\DB\Select $select, $table, array $fields = [], $mode = false)
    {
        $this->resourceAdapter->exec('SET FOREIGN_KEY_CHECKS = 0;');
        ...
    }

```
