### ISSUE TITLE
customer grid

### ISSUE THREAD

**Issue by antuz88** [magento/data-migration-tool#53]
Hi,
i have migrated my db from magento 1.8.0 to 2.0.
My orders,product and customers was migrated correctly but in customer grid i receive empty results with message: We couldn't find any records.
If i try to edit a customers from an order i can do it.

EDIT: my table customer_entity is populated but customer_grid_flat is empty. If i add manually in db a record on customer_grid_flat i can display the record on magento backend.

Another issues, when i try to add new customer i receive a blank page and the log is:

PHP Fatal error: Allowed memory size of 2147483648 bytes exhausted (tried to allocate 79 bytes) in /var/www/magetest/vendor/magento/module-eav/Model/Entity/Collection/AbstractCollection.php on line 486

i have set in .htaccess and php.ini the php_value to 2048M but not solved it.

Someone can help me?

Thanks

**Comment by victor-v-rad** [comment]
Hi,

reindexing and clearing cache should solve your problem. Run in command line:
`php bin/magento indexer:reindex && php bin/magento cache:clean`

**Comment by antuz88** [comment]
Hi victor-v-rad,
I had already tried to reindexing and clearing cache but the problem is not solved.

**Comment by victor-v-rad** [comment]
Hi,
I have just migrated 1.8.1.0 (without any extensions) to Magento 2.0.0 and everything is ok (customer_grid_flat has expected records). Product/order grids shows its data in admin panel of Magento 2. 
I assume you have some extensions that changed your DB in Magento 1 in the way that migration did not pass correctly. Please read carefully the official [documentation](devdocs.magento.com/guides/v2.0/migration/bk-migration-guide.html). You may miss something.

**Comment by antuz88** [comment]
Hi,
i have many extensions installed on my magento 1.8.0.Probably my extensions have changed my DB, but how can i migrate data now? Your link for documentation is in 404 error.

Thanks

**Comment by victor-v-rad** [comment]
http://devdocs.magento.com/guides/v2.0/migration/bk-migration-guide.html

**Comment by antuz88** [comment]
Thanks, i can't find a solution... so i'm trying to restart migration  trough ub migration data :(

**Comment by andidhouse** [comment]
It would really be helpful to know how extensions can interrupt the migration process. I thought not mapped or existing fields/tables are shown before installation in the check. 

We have also many extensions running on 1.7 and have problems that the migration process passes without errors but in magento 2. we have some bad sites which do not function.

Also finding no solution in the documentation.

**Comment by ilol** [comment]
@andidhouse, Try [Magento Code Migration Tool](https://github.com/magento/code-migration) to port extentions **before ** data migration.

**Comment by andidhouse** [comment]
Hi ilol,
many thanks for your answer. 
We do not want to port any 1.x module to the 2.0 version. For us it is perfect just to migrate the data and have the extensions replaced by new ones for magento 2. 

We still have no solution for our problems in data migration an really have no idea where we can get help but here :-/.

**Comment by ilol** [comment]
You can contact with me and tell me your story. I will try to help you. My skype is ilya.oleynik

**Comment by andidhouse** [comment]
Hi Illia,

many thanks for your answer.

Our story is:
https://github.com/magento/data-migration-tool/issues/48

We try at the moment to migrate our 1.7.0.2 store to magento2.
After fixing some bugs of the toll (see fixes file attached) the settings and data migration succeeds without a problem.
But we have one big problem we can´t solve.

After migration if we want to show the backend product grid the site has errors - if we fix this in the magento 2 database the products are shown in the admin product grid but if we try to access a product just the headline of the product is shown.

Maybe the „backup_tables“ issue is fixed here:
https://github.com/victor-v-rad/data-migration-tool/commit/8465c60b18a924d83b766fabeff4a8fe653c6e46

But the product problem still remains and we have no idea how to solve this.

Pls fins also attached our „Ignore List“ - but i think this is not the problem as with a complete fresh magento 1.7.0.2 database the migration works without a problem.
We have several extensions in our magento 1.7 running - this might be the problem but we can´t find a way (or error log) to solve this.

It would be great if you could help us here to find and solve the problem.
If you want we can send you the magent0 1.7 database as sql file for testing.

Many thanks!

André





After solving some bugs in the tool (pls see

**Comment by mitsprajapati** [comment]
Hi 

I am also facing same issue, I migrated from 1.9 to Magento 2. All seems to be working fine except customer_grid_flat table is empty. Even after reindex this table is empty and not showing any error while reindex. Because of this I dont see customer data in backend and while placing order in frontend I am getting some error.

Strange thing is it shows status Processing for customer grid reindex which is not changing.

NOTICE : while migration I see following warning message for customer migration.
Mage2CustomerAddressEntityText not valid value 

I dont know hoe to fix this issue can some one help here please.

Thanks,
Mitesh

**Comment by radiojoe** [comment]
How did you reindex? I was having this same issue, but running this command fixed it:

./bin/magento indexer:reindex

**Comment by mitsprajapati** [comment]
Hi 
I also run same command and also try with indexer:reindex customer_grid as well.

But still not showing customer in admin grid. I checked customer grid table but it is not creating any record in that table.

So now sure what to do , do you have any suggestion.

**Comment by ND17** [comment]
Any one find solution of not showing customer in admin customer grid?

**Comment by victor-v-rad** [comment]
Hi,

Try this fix #66

**Comment by ND17** [comment]
@victor-v-rad this is for product grid and i have changed additional_attribute_table entry but its not showing any data in customer grid

**Comment by ND17** [comment]
Got the solution 
In indexer_state change customer_grid value "working" from "invalid" and than run php -d memory_limit=1024M bin/magento indexer:reindex

after this all customer shows in admin grid

**Comment by victor-v-rad** [comment]
Great! I am closing the issue

**Comment by Avinashsain** [comment]
Hello,

I am facing the same issue and I try all given solutions.

Thanks
