### ISSUE TITLE
[Migration\Exception] Volume Check failed - EAV Step

### ISSUE THREAD

**Issue by dev4q1** [magento/data-migration-tool#69]
Hi,

I am getting this error

`[2016-03-08 12:38:36][ERROR]: Source and Destination attributes mismatch. Attribute id: 383`

Unfortunately I can't find the corresponding file/source to fix this problem. What does this error mean? and how can I fix this?

I am migrating from magento 1.9.2.3/.4 to magento 2.0.2

Thanks for the help!

**Comment by redboxmarcins** [comment]
Error comes from `Migration\Step\Eav\Volume::validateEavAttributes()`

which means that your eav attribute code is different in the source table and destination table

run sql query on both old M1 and new M2 databases:

`SELECT attribute_id, attribute_code FROM `eav_attribute` WHERE attribute_id = 383;`

then you can compare

**Comment by dev4q1** [comment]
When running the query on the M1 DB I get

attribute_id 383
attribute_code group_price

For the M2 DB I get nothing as result.

Can I insert the missing record manually into the M2 DB to fix the issue?

**Comment by kennylawrence** [comment]
since this issue keeps popping up for various people (missing attribute entry for the "group_price" in catalog_eav_attributes), is it a bug? My M1.9.2.2 setup has zero custom code, and only a small number of extensions. Since the failure is during the comparison stage after copying was to occur, doesn't it mean that for some reason the copying did not occur? Is if that is the case, why? Is the checking the bug or is the failure to copy the bug?

Further, why is no one responsive on this board? The data-migration-tool is an integral part of Magento 2, and the docs say explicitly that versions must match. Yet they have released two new versions without updating the migration tool!

**Comment by ilol** [comment]
The update is in progress. 2.0.5 patch will be released soon

**Comment by ilol** [comment]
MAGETWO-52162

**Comment by kennylawrence** [comment]
Hi again, I just wanted to comment that this is still an issue in 2.1. I still get the group_price attribute mismatch between source and destination.

Can someone just please confirm that it's OK to just delete the attribute from the eav_attribute table?

**Comment by victor-v-rad** [comment]
>Can someone just please confirm that it's OK to just delete the attribute from the eav_attribute table? 

As you can see group_price is already in ingnore list in etc/ce-to-ce/eav-attribute-groups.xml.dist . So the attribute it not needed in Magento 2

**Comment by kennylawrence** [comment]
@victor-v-rad no need to be snarky - surely you know in the software world that it is not a good idea to make assumptions about others' code. I am simply someone who is good at following directions (ie, magento documentation) and who feels insecure when those instructions still result in error messages that were reported months ago..(and claimed to have been fixed!).. and yet the knowledgeable parties will not reply with a yes/no answer to a simple question. I'm sure you have encountered situations where making assumptions led to lost time.

**Comment by victor-v-rad** [comment]
The issue with group_price is in our backlog. Internal ticket MAGETWO-52161 The reason why it is not solved yet is that the backlog is huge

**Comment by victor-v-rad** [comment]
@dev4q1 @redboxmarcins @kennylawrence 
Please recheck the issue on the latest version of the tool and close if it is fixed

**Comment by kennylawrence** [comment]
fixed for me
